
server:
  port: 9191

spring:
  application:
    name: inventory-service
  data:
    mongodb:
      uri: mongodb://backendUser:backendUser@localhost:27017/inventory



eureka:
  ## This will allow us to register multiple instance of same service because since we use 0 as port it going to have duplicate instance id
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
